
#source 'https://git.coding.net/hging/Specs.git'

platform :ios, '9.0'

use_frameworks!

def pods
    pod 'AsyncDisplayKit'
    #pod 'Appsee'
    pod 'DeviceUtil'
    pod 'FXBlurView'
    pod 'TPKeyboardAvoiding'
    pod 'pop'
    pod 'SocketRocket'
    pod 'JPush'
    #pod 'Fabric'
    
    pod 'Bugly'
    pod 'Kanna', '~>4.0.0'
    pod 'AutoReview'
    pod 'KeypathObserver'
    pod 'RxSwift', '~>4.0'
    pod 'RxCocoa', '~>4.0'
    pod 'ReSwift', '~>4.0'
    pod 'RealmSwift', '~>3.14.0'
    pod 'MonkeyKing', '~>1.13.0'
    pod 'Proposer', '~>1.2.1'
    pod 'Ruler', '~>3.0.0'
    pod 'KeyboardMan', '~> 1.2.3'
    pod 'Navi', '~>1.1.1'
    pod 'Alamofire' 
    pod 'Kingfisher' 
    pod 'AudioBot', '~>1.2.2'
end

target 'Yep' do
    pods

    target 'YepTests' do
        inherit! :search_paths
    end
end

target 'YepKit' do
    pod 'Navi', '~>1.1.1'
    pod 'Ruler', '~>3.0.0'
    pod 'Alamofire' 
    pod 'RealmSwift', '~>3.14.0'
end

target 'FayeClient' do
    pod 'SocketRocket'
end

target 'OpenGraph' do
    pod 'Kanna', '~>4.0.0'
    pod 'Alamofire' 
    
    target 'OpenGraphTests' do
        inherit! :search_paths
    end
end

target 'YepShare' do
    pod 'RealmSwift', '~>3.14.0'
end

post_install do |installer|
    puts 'Allow app extension api only:'
    installer.pods_project.targets.each do |target|
        case target.name
        when 'SocketRocket'
            target.build_configurations.each do |config|
                config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'YES'
                puts 'X...' + target.name
            end
        else
            puts '....' + target.name
        end
#         target.build_configurations.each do |config|
#                 config.build_settings['SWIFT_VERSION'] = '3.0'
#                 config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
#         end
    end
end

